### PR TITLE
removed deprecated version line from docker-compose

### LINKED ISSUE #584: unable to register upload plan (pilot project)
1. Login to DMP Tool production instance
2. Member is from "University of California, Riverside"
3. User went to "Upload plan" feature and uploaded document and entered project name ("PPoSS: Planning: Dynamic Big Graph Store for High-Throughput and Secure Distributed Query Processing")
4. User completed all sections, and made sure PIs and primary contact were designated. 
5. When she clicked 'Register and Return to Dashboard,' she received this error: "There was a problem registering your plan. Please try again later."
6. I checked her data entry and nothing appeared unusual except that there are 5 PIs listed (not sure if there is a limit). I tried to register the same DMP, and received the same error message (sorry, I'm working a conference and cannot go through all steps right now).

### PR DESCRIPTION
**Pull request by briri**
Fixes #584.

Changes proposed in this PR:
- minor update to the React page to trim leading and trailing whitespace from the URL
- removed a deprecated `version` statement from the docker-compose file
- Rails added a foreign key constraint was added to the schema.rb. I am surprised this was not already in place.

### CODE REVIEW

File: react-client/src/models.js [hunk 1]
```diff
@@ -324,7 +324,7 @@ export class DataRepository extends Model {
   set title(val) { this.setData("host.title", val); }
 
   get url() { return this.getData("host.url", ""); }
-  set url(val) { this.setData("host.url", val); }
+  set url(val) { this.setData("host.url", val?.trim()); }
```
Comment (jupiter007) [inline react-client/src/models.js]: @briri , you shouldn't need to use optional chaining in front of the "trim()" method, because JavaScript automatically handles the case where the value is null.

Comment (briri) [reply react-client/src/models.js]: Ah. I did not realize that. I just updated

Comment (jupiter007) [reply react-client/src/models.js]: @briri thanks for making the change.

**Review by jupiter007 — APPROVED** [review]
